### ISSUE TITLE
Device manager

### ISSUE THREAD

**Issue by johnmarcou** [shelmangroup/coreos-gpu-installer#1]
Hello, and thank you a lot for this repo.

Reproduce
-----------
I installed the nvidia driver:
```
kubectl apply -f https://raw.githubusercontent.com/shelmangroup/coreos-gpu-installer/master/daemonset.yaml
```

Then the device manager:

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/kubernetes/master/cluster/addons/device-plugins/nvidia-gpu/daemonset.yaml
```

Then submit a pod:
```
kind: Pod
apiVersion: v1
metadata:
  name: nvidia-pod
spec:
  containers:
    - name: nvidia
      image: 'nvidia/cuda'
      command:
        - bash
        - -c
        - "exec sleep 60000"
      resources:
        limits:
          nvidia.com/gpu: 1
```

The issue
---------

I just have a little issue, the bin/lib are not available from within the pod.
When I copy the content of `/opt/nvidia` to `/home/kubernetes/bin/nvidia` on the host, everything works like a charm.

After a docker inspect on my container, I figure out the mount was mounting on `/home/kubernetes/bin/nvidia`,:
```
            {
                "Type": "bind",
                "Source": "/home/kubernetes/bin/nvidia",
                "Destination": "/usr/local/nvidia",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
```
but the local host path should be `/opt/nvidia` as specified in the installation driver:
```
          - name: NVIDIA_INSTALL_DIR_HOST
            value: /opt/nvidia
```

Investigation
------------
I tried to redeploy the driver-installer-deamonset with `/home/kubernetes/bin/nvidia` as `NVIDIA_INSTALL_DIR_HOST` and updated `volume`, but the init-pod return an error: 
```
overlayfs: filesystem on 'bin' not supported as upperdir
```

I don't know how I could setup that information on the Device Manager, and it seems to be hardcoded https://github.com/GoogleCloudPlatform/container-engine-accelerators/blob/70a1113ee4ceb413e21c54ca943bc2f4b984117d/cmd/nvidia_gpu/nvidia_gpu.go#L33?

I am running a wrong version of the device manager ?
What version of device manager daemonSet manifest are you using ?

Thank you.

**Comment by lsjostro** [comment]
```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nvidia-gpu-device-plugin
  namespace: kube-system
  labels:
    k8s-app: nvidia-gpu-device-plugin
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  template:
    metadata:
      labels:
        k8s-app: nvidia-gpu-device-plugin
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      priorityClassName: system-node-critical
      tolerations:
      - key: "nvidia.com/gpu"
        effect: "NoSchedule"
        operator: "Exists"
      hostNetwork: true
      hostPID: true
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: dev
        hostPath:
          path: /dev
      containers:
      - image: "k8s.gcr.io/nvidia-gpu-device-plugin@sha256:0e79da6998a61257585e0d3fb5848240129f0fa5b4ad972dfed4049448093c33"
        command: ["/usr/bin/nvidia-gpu-device-plugin", "-logtostderr", "-host-path=/opt/nvidia"]
        name: nvidia-gpu-device-plugin
        resources:
          requests:
            cpu: 50m
            memory: 10Mi
          limits:
            cpu: 50m
            memory: 10Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: device-plugin
          mountPath: /device-plugin
        - name: dev
          mountPath: /dev
```
