### ISSUE TITLE
Driver installation not reboot proof

### ISSUE THREAD

**Issue by thcdrt** [shelmangroup/coreos-gpu-installer#11]
Hello,

Thanks for your work about nvidia drivers installation on coreOS, it works really great.

I just have an issue when I reboot the server where the drivers are installed.

Indeed, the command nvidia-smi does not work anymore:
`NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.`

It seems like some kernel modules are not loaded anymore:
`$ lsmod | grep nvidia` returns an empty output.

Do you have an idea about what should be done to make it work again after a reboot ?

Thanks,
Thomas

**Comment by thcdrt** [comment]
I found a solution to make it work at reboot time:

`sudo modprobe ipmi_devintf

sudo insmod "/opt/nvidia/drivers/nvidia.ko"

sudo insmod "/opt/nvidia/drivers/nvidia-uvm.ko" 

sudo insmod "/opt/nvidia/drivers/nvidia-modeset.ko" `

I'll configure it in the /etc/modules-load.d directory.

Thomas

**Comment by seh** [comment]
After running the driver installer container, we run the following commands:
```
sudo ln -s /opt/nvidia/drivers/nvidia{,-uvm,-drm}.ko /lib/modules/$(uname -r)/
sudo depmod
```

**Comment by thcdrt** [comment]
How do you run it ?

I already tried this but /lib/modules is a read-only filesystem.

**Comment by seh** [comment]
We mount an overlay filesystem atop _/lib/modules_.

From our Container Linux Config file:
```yaml
  files:
  - filesystem: root
    path: /etc/fstab
    contents:
      inline: overlay /lib/modules overlay lowerdir=/lib/modules,upperdir=/opt/modules,workdir=/opt/modules.wd 0 0
    mode: 420
```
